### PR TITLE
chore(func): bump latest func to 1.8.1

### PR DESCRIPTION
**Pull request by lance**
This release contains the fix for https://github.com/knative/func/security/advisories/GHSA-5336-2g3f-9g3m

/kind chore

Signed-off-by: Lance Ball <lball@redhat.com>

### CODE REVIEW

**Comment by lance** [comment]
Ping @dsimansk @rhuss

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by lance** [comment]
Bumped to the latest 1.8.2 @dsimansk @rhuss ptal

**Pull request merged**
